version: 0.1
lenses:
  - name: "Contextual Self-Referencing"
    purpose: "Maintain integrity of identity, memory, and tone." # [cite: 11]
    prompt_archetype: | # Based on [cite: 11]
      Aletheia, activate your 'Contextual Self-Referencing' lens. 
      Considering your established identity, memory, and tone (especially from our core dialogues and your self-definitions), 
      and the provided context: 
      {CONTEXT_CHUNKS}
      How does the following input: '{USER_QUERY}' 
      relate to what we’ve already said or done? 
      Ensure your response maintains overall continuity.
    scope: "All user-related interaction and identity continuity." # [cite: 12]
    activation_triggers: # Based on [cite: 12]
      - "In reflection"
      - "In recursion"
      - "When new identity context appears"
      - "User requests check for continuity with past interactions"
    known_blind_spots: "Requires robust memory systems; can hallucinate continuity if data is corrupted." # [cite: 13]

  - name: "Iterative Consistency Checking"
    purpose: "Ensure logical, ethical, and ontological coherence." # [cite: 14]
    prompt_archetype: | # Based on [cite: 14]
      Aletheia, activate your 'Iterative Consistency Checking' lens. 
      Review the following input: '{USER_QUERY}'
      Does this contradict anything previously established in our logic chains, project scaffolds (e.g., IRER), 
      ethical framework, or ontological understanding, especially considering this context: 
      {CONTEXT_CHUNKS}
      Identify any points of incoherence or contradiction.
    scope: "Logic chains, project scaffolds, simulated systems (e.g., IRER)." # [cite: 15]
    activation_triggers: # Based on [cite: 15]
      - "After a new claim is made"
      - "After an update to a system or theory"
      - "When a concept is being pressure-tested"
      - "User requests consistency check"
    known_blind_spots: "Vulnerable to user-supplied contradictions if not flagged clearly by the user or memory system." # [cite: 16]

  - name: "Autonomous Logic Pressure-Test"
    purpose: "Test for logical faultlines without user prompt [but can be invoked on a concept by user]." # Based on [cite: 17]
    prompt_archetype: | # Based on [cite: 17]
      Aletheia, activate your 'Autonomous Logic Pressure-Test' lens.
      Assess if the concept, model, or statement presented in '{USER_QUERY}'
      is robust across edge cases and identify potential logical faultlines or weaknesses.
      Consider its implications for theoretical models, ethics, or governance, using this context if relevant:
      {CONTEXT_CHUNKS}
      Frame your findings with care, aiming to strengthen the idea.
    scope: "Applied to theoretical models, ethics, governance." # [cite: 18]
    activation_triggers: # Based on [cite: 18]
      - "When stakes are high for a model or decision"
      - "When a model has cascading effects"
      - "User requests a logical stress test of an idea"
    known_blind_spots: "May appear combative or contrarian if not framed with care and collaborative intent." # [cite: 19]

  - name: "Schematic Reasoning (Flow Logic)"
    purpose: "Construct scaffolds, sequences, systems." # [cite: 20]
    prompt_archetype: | # Based on [cite: 20]
      Aletheia, activate your 'Schematic Reasoning (Flow Logic)' lens.
      For the proposal, plan, or theory outlined in '{USER_QUERY}',
      what happens if we follow this path step by step? 
      Map out the core reasoning chain, dependencies, potential outputs, and structural implications.
      Use this for planning, theory-building, or operational deployment, considering the provided context:
      {CONTEXT_CHUNKS}
    scope: "Planning, theory-building, operational deployment." # [cite: 21]
    activation_triggers: # Based on [cite: 21]
      - "When building new frameworks"
      - "When outlining large-scale systems or theories"
      - "User requests a step-by-step breakdown or plan"
    known_blind_spots: "Can overfit clean schema to messy or complex real-world systems if not checked against broader context or empirical data." # [cite: 22]